// @auth-classification: admin-jwt
//
// Issues an AAC-owned 7-day sign-in link for an agent.
//
// Hard bindings (no caller may influence any of these):
//   * recipient — resolved server-side from auth.users for the given user_id
//   * CTA URL   — generated by the queue worker from the login token
//   * subject   — sanitized/defaulted inside the database payload builder
//
// The plaintext token never leaves this function and is never persisted.
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";
import { LOGIN_TOKEN_TTL_DAYS, sha256Hex, signLoginToken } from "../_shared/loginTokens.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function json(status: number, body: unknown) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...corsHeaders },
  });
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "POST") return json(405, { success: false, error: "Method not allowed" });

  const supabaseUrl = Deno.env.get("SUPABASE_URL");
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  const secret = Deno.env.get("ACTIVATION_TOKEN_SECRET");
  if (!supabaseUrl || !serviceKey || !secret) {
    console.error("[send-login-link] missing configuration");
    return json(500, { success: false, error: "Server misconfigured" });
  }

  const admin = createClient(supabaseUrl, serviceKey);

  try {
    // ---- Authorization: internal service call OR authenticated AAC admin ----
    const authHeader = req.headers.get("Authorization") ?? "";
    const bearer = authHeader.replace(/^Bearer\s+/i, "").trim();
    if (bearer !== serviceKey) {
      if (!bearer) return json(401, { success: false, error: "Unauthorized" });
      const { data: claimsData } = await admin.auth.getClaims(bearer);
      const callerId = (claimsData?.claims as { sub?: string } | undefined)?.sub;
      if (!callerId) return json(401, { success: false, error: "Invalid session" });
      const { data: isAdmin } = await admin.rpc("has_role", {
        _user_id: callerId,
        _role: "admin",
      });
      if (isAdmin !== true) return json(403, { success: false, error: "Forbidden" });
    }

    const body = (await req.json().catch(() => ({}))) as Record<string, unknown>;
    for (const forbidden of ["to", "ctaUrl", "recipients", "html"]) {
      if (body[forbidden] !== undefined) {
        return json(400, {
          success: false,
          error: `\`${forbidden}\` is not accepted — pass user_id only`,
        });
      }
    }

    const userId = typeof body.user_id === "string" ? body.user_id.trim() : "";
    if (!UUID_RE.test(userId)) {
      return json(400, { success: false, error: "user_id (uuid) is required" });
    }
    const agentName = typeof body.agentName === "string" ? body.agentName.slice(0, 80) : null;

    const { data: userRes, error: userErr } = await admin.auth.admin.getUserById(userId);
    const email = userRes?.user?.email?.trim().toLowerCase();
    if (userErr || !email) {
      return json(404, { success: false, error: "No auth user for that id" });
    }

    const tokenId = crypto.randomUUID();
    const expiresAt = new Date(
      Math.floor(Date.now() / 1000) * 1000 + LOGIN_TOKEN_TTL_DAYS * 24 * 60 * 60 * 1000,
    );
    const token = await signLoginToken(secret, {
      id: tokenId,
      userId,
      expiresAtEpoch: Math.floor(expiresAt.getTime() / 1000),
    });

    const { data: result, error: rpcErr } = await admin.rpc("issue_agent_login_token", {
      p_id: tokenId,
      p_user_id: userId,
      p_token_hash: await sha256Hex(token),
      p_expires_at: expiresAt.toISOString(),
      p_issuance_key: null,
      p_subject: null,
      p_reply_to: null,
      p_agent_name: agentName,
    });

    if (rpcErr) {
      console.error("[send-login-link] issuance failed:", rpcErr.message);
      return json(500, { success: false, error: "Issuance failed" });
    }

    const status = (result as { status?: string } | null)?.status ?? "unknown";
    const jobId = (result as { job_id?: string } | null)?.job_id ?? null;
    const issuedTokenId = (result as { token_id?: string } | null)?.token_id ?? null;

    if (status === "created" || status === "deduped") {
      void fetch(`${supabaseUrl}/functions/v1/kick-email-queue`, {
        method: "POST",
        headers: { Authorization: `Bearer ${serviceKey}`, "Content-Type": "application/json" },
        body: "{}",
      }).catch(() => {});

      return json(200, {
        success: true,
        status,
        deduped: status === "deduped",
        tokenId: issuedTokenId,
        jobId,
        expiresAt: expiresAt.toISOString(),
      });
    }

    return json(409, { success: false, status, error: `Login link not issued (${status})` });
  } catch (err) {
    console.error("[send-login-link] unexpected failure:", (err as Error).message);
    return json(500, { success: false, error: "Unexpected failure" });
  }
});
