// @auth-classification: admin-or-internal
//
// Issues the AAC-owned License Verified activation email.
//
// Hard bindings (no caller may influence any of these):
//   * recipient  — resolved server-side from auth.users for the given user_id
//   * CTA URL    — generated by the queue worker from the activation token
//   * subject    — sanitized/defaulted inside the database payload builder
//
// The request body accepts ONLY { user_id }. Arbitrary `to`, recipient
// arrays, and `ctaUrl` overrides are rejected outright.
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";
import {
  ACTIVATION_TOKEN_TTL_DAYS,
  sha256Hex,
  signActivationToken,
} from "../_shared/activationTokens.ts";
import { findDeletedAgent } from "../_shared/checkDeletedAgent.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function json(status: number, body: unknown) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...corsHeaders },
  });
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "POST") return json(405, { success: false, error: "Method not allowed" });

  const supabaseUrl = Deno.env.get("SUPABASE_URL");
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  const secret = Deno.env.get("ACTIVATION_TOKEN_SECRET");
  if (!supabaseUrl || !serviceKey || !secret) {
    console.error("[send-license-verified-email] missing configuration");
    return json(500, { success: false, error: "Server misconfigured" });
  }

  const admin = createClient(supabaseUrl, serviceKey);

  try {
    // ---- Authorization: internal service call OR authenticated AAC admin ----
    const authHeader = req.headers.get("Authorization") ?? "";
    const bearer = authHeader.replace(/^Bearer\s+/i, "").trim();
    let isInternal = bearer === serviceKey;

    if (!isInternal) {
      if (!bearer) return json(401, { success: false, error: "Unauthorized" });
      const { data: userData } = await admin.auth.getUser(bearer);
      const callerId = userData?.user?.id;
      if (!callerId) return json(401, { success: false, error: "Unauthorized" });
      const { data: isAdmin } = await admin.rpc("has_role", {
        _user_id: callerId,
        _role: "admin",
      });
      if (isAdmin !== true) return json(403, { success: false, error: "Forbidden" });
      isInternal = false;
    }

    const body = (await req.json().catch(() => ({}))) as Record<string, unknown>;

    // Explicitly reject legacy caller-controlled fields rather than ignoring
    // them, so no stale integration silently keeps working.
    for (const forbidden of ["to", "ctaUrl", "recipients", "html"]) {
      if (body[forbidden] !== undefined) {
        return json(400, {
          success: false,
          error: `\`${forbidden}\` is no longer accepted — pass user_id only`,
        });
      }
    }

    const userId = typeof body.user_id === "string" ? body.user_id.trim() : "";
    if (!UUID_RE.test(userId)) {
      return json(400, { success: false, error: "user_id (uuid) is required" });
    }
    const acknowledgeDeleted = body.acknowledgeDeleted === true;
    const agentName = typeof body.agentName === "string" ? body.agentName.slice(0, 80) : null;
    // "initial" is idempotent on the approval event; "resend" mints a fresh
    // token (admin-triggered, minute-bucketed so double-clicks collapse).
    const mode = body.mode === "resend" ? "resend" : "initial";

    // ---- Server-side recipient resolution (never trusted from the caller) ----
    const { data: userRes, error: userErr } = await admin.auth.admin.getUserById(userId);
    const email = userRes?.user?.email?.trim().toLowerCase();
    if (userErr || !email) {
      return json(404, { success: false, error: "No auth user for that id" });
    }

    if (!acknowledgeDeleted) {
      const deletedMatch = await findDeletedAgent(admin, email);
      if (deletedMatch) {
        return json(409, {
          success: false,
          code: "previously_deleted",
          match: deletedMatch,
        });
      }
    }

    // ---- Pre-generate the record id so it can be signed into the token ----
    const tokenId = crypto.randomUUID();
    const expiresAt = new Date(
      Math.floor(Date.now() / 1000) * 1000 + ACTIVATION_TOKEN_TTL_DAYS * 24 * 60 * 60 * 1000,
    );
    const token = await signActivationToken(secret, {
      id: tokenId,
      userId,
      expiresAtEpoch: Math.floor(expiresAt.getTime() / 1000),
    });

    // Token row + transactional email job, one transaction, idempotent on the
    // approval event. The plaintext token never leaves this function.
    const rpcName = mode === "resend"
      ? "reissue_agent_activation_token"
      : "issue_agent_activation_token";

    const { data: result, error: rpcErr } = await admin.rpc(rpcName, {
      p_id: tokenId,
      p_user_id: userId,
      p_token_hash: await sha256Hex(token),
      p_expires_at: expiresAt.toISOString(),
      p_subject: null,
      p_reply_to: null,
      p_agent_name: agentName,
      // An admin who acknowledged the "previously deleted" warning can pass the
      // database-side tombstone gate too; every other gate stays enforced.
      p_allow_previously_deleted: acknowledgeDeleted,
    });

    if (rpcErr) {
      console.error("[send-license-verified-email] issuance failed:", rpcErr.message);
      return json(500, { success: false, error: "Issuance failed" });
    }

    const status = (result as { status?: string } | null)?.status ?? "unknown";
    const jobId = (result as { job_id?: string } | null)?.job_id ?? null;
    const issuedTokenId = (result as { token_id?: string } | null)?.token_id ?? null;

    if (status === "created" || status === "deduped") {
      void fetch(`${supabaseUrl}/functions/v1/kick-email-queue`, {
        method: "POST",
        headers: { Authorization: `Bearer ${serviceKey}`, "Content-Type": "application/json" },
        body: "{}",
      }).catch(() => {});

      return json(200, {
        success: true,
        status,
        deduped: status === "deduped",
        tokenId: issuedTokenId,
        jobId,
        successCount: 1,
      });
    }

    // previously_deleted / ineligible / blocked / already_live / no_recipient
    const reasons: Record<string, string> = {
      previously_deleted:
        "This address was deleted previously — acknowledge the deletion warning to send anyway.",
      ineligible:
        "This agent is not eligible for a setup link (not verified, rejected, or already activated).",
      blocked: "A setup link for this agent is being redeemed right now. Try again in a few minutes.",
      already_live: "A setup link is already live for this agent. Use Resend to replace it.",
      no_recipient: "This agent has no valid email address on file.",
    };
    return json(422, {
      success: false,
      status,
      code: status,
      error: reasons[status] ?? `Could not send setup email (${status}).`,
      successCount: 0,
    });
  } catch (err) {
    console.error("[send-license-verified-email] error:", err);
    return json(500, { success: false, error: (err as Error)?.message ?? "Unknown error" });
  }
});
